name: Post sync agenda

on:
  workflow_dispatch:
  repository_dispatch:
    types:
      - post-agenda

jobs:
  post-agenda:
    name: Post sync agenda to Zulip
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/ponylang/pony-sync-helper-ci-builder:release
    steps:
      - uses: actions/checkout@v4.1.1
      - name: Today's date
        run: echo "DATE=$(date +%Y-%m-%d)" >> "$GITHUB_ENV"
      - name: Build sync-helper
        run: |
          corral fetch
          corral run -- ponyc -Dopenssl_0.9.0
      - name: Run sync-helper
        run: |
          {
            echo 'AGENDA<<EOF'
            ./pony-sync-helper --label "discuss during sync" --org ponylang --github_token "$PONY_SYNC_HELPER_GITHUB_TOKEN"
            echo 'EOF'
          } >> "$GITHUB_ENV"
        env:
          PONY_SYNC_HELPER_GITHUB_TOKEN: ${{ secrets.PONYLANG_MAIN_API_TOKEN }}
      - name: Post agenda
        uses: zulip/github-actions-zulip/send-message@e4c8f27c732ba9bd98ac6be0583096dea82feea5
        with:
          api-key: ${{ secrets.ZULIP_SYNC_EVENT_API_KEY }}
          email: ${{ secrets.ZULIP_SYNC_EVENT_EMAIL }}
          organization-url: 'https://ponylang.zulipchat.com/'
          to: sync
          type: stream
          topic: ${{ env.DATE }}
          content: ${{ env.AGENDA }}
