name: Post good first issues

on:
  workflow_dispatch:
  schedule:
    - cron: '0 14 * * Mon'

jobs:
  post-ISSUES:
    name: Post good first issues to Zulip
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/ponylang/pony-sync-helper-ci-builder:release
    steps:
      - uses: actions/checkout@v3
      - name: Today's date
        run: echo "DATE=$(date +%Y-%m-%d)" >> "$GITHUB_ENV"
      - name: Build sync-helper
        run: |
          corral fetch
          corral run -- ponyc -Dopenssl_0.9.0
      - name: Run sync-helper
        run: |
          {
            echo 'ISSUES<<EOF'
            ./pony-sync-helper --label "good first issue" --org ponylang --github_token "$PONY_SYNC_HELPER_GITHUB_TOKEN"
            echo 'EOF'
          } >> "$GITHUB_ENV"
        env:
          PONY_SYNC_HELPER_GITHUB_TOKEN: ${{ secrets.PONYLANG_MAIN_API_TOKEN }}
      - name: Post Issues
        uses: zulip/github-actions-zulip/send-message@b62d5a0e48a4d984ea4fce5dd65ba691963d4db4
        with:
          api-key: ${{ secrets.ZULIP_SYNC_EVENT_API_KEY }}
          email: ${{ secrets.ZULIP_SYNC_EVENT_EMAIL }}
          organization-url: 'https://ponylang.zulipchat.com/'
          to: contribute to Pony
          type: stream
          topic: Good first issues as of ${{env.DATE}}
          content: ${{ env.ISSUES }}
