name: PR

on: pull_request

concurrency:
  group: pr-${{ github.ref }}
  cancel-in-progress: true

jobs:
  superlinter:
    name: Lint bash, docker, markdown, and yaml
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Lint codebase
        uses: docker://github/super-linter:v3.8.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_ALL_CODEBASE: true
          VALIDATE_BASH: true
          VALIDATE_DOCKERFILE: true
          VALIDATE_MD: true
          VALIDATE_YAML: true

  linux:
    name: Verify PR builds on Linux with most recent ponyc nightly
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/ponylang/pony-sync-helper-ci-builder:release
    steps:
      - uses: actions/checkout@v3
      - name: Builds with the most recent ponyc nightly
        run: |
          corral fetch
          corral run -- ponyc -Dopenssl_0.9.0
